
title: Laia Freixas Mateu
email: lfreixasmateu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a computer scientist that enjoys playing with hardware
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

show_downloads: false
google_analytics:
remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "dark"
plugins:
  - jekyll-include-cache
author:
  name             : "Laia Freixas"
  avatar           : "/img/waddles.png"
  bio              : "I am a computer scientist that enjoys playing with hardware"
  location         : "Oxford, UK"
  email            : "lfreixasmateu@gmail.com"
  github           : "laiaaa0"
  linkedin         : "laiafreixas"
  links:
      - label: "About me"
        icon: ""
        url: "/about.html"
        
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:    
      layout: single 
      author_profile: true
      read_time: true
      show_date: true


