
title: Laia Freixas Mateu
email: lfreixasmateu@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I am a computer scientist that enjoys playing with hardware
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: laiafreixas
github_username:  laiaaa0

logo: /img/waddles.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed
